version: "3"

services:
  mc:
    image: itzg/minecraft-server
    container_name: mc-server
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
    volumes:
      - ./data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.minecraft.entrypoints=minecraft"
      - "traefik.tcp.routers.minecraft.rule=HostSNI(`*`)"
      - "traefik.tcp.services.minecraft.loadbalancer.server.port=25565"
    networks:
      - proxy_net